### PR TITLE
Jac design fixes

### PR DESCRIPTION
**Pull request by scabbiaza**
Notes:
1. Update bower components
2. Pls check robots/index. I may miss something by merging

### CODE REVIEW

**Comment by ivan-kleshnin** [comment]
`/public` is in `.gitignore`. Why is it commited?

**Comment by ivan-kleshnin** [comment]
Pagination misses `.active` class for current item.

**Comment by ivan-kleshnin** [comment]
Look for typo `cick`

**Comment by scabbiaza** [comment]
> 1. /public is in .gitignore. Why is it commited?
Because this commits were before merging with new version.

Check the branch: we don't have this folder under VCS

> Pagination misses .active class for current item.
I used `disabled`. So `active` or `disabled`, I'm confused?
https://github.com/Paqmind/react-starter/tree/jac-design-fixes

> Look for typo cick
Typo is fixed

**Comment by ivan-kleshnin** [comment]
> I used disabled. So active or disabled, I'm confused?

Need both: `.disabled` for disabling Prev and Next and `.active` for activating current.
I already done this, don't bother.

**Pull request merged**
